apiVersion: v1
kind: Pod
metadata:
  name: nginx-sql-pod
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
    - name: sqldb-container
      image: mysql:latest
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: topsecret
              key: root-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: topsecret
              key: database-name
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: topsecret
              key: database-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: topsecret
              key: database-password
